version: "^3"

services:
  yolo-backend:
    build: ./backend
    depends_on:
      - yolo-mongodb-alpine
    ports:
      - "5000:5000"
    networks:
      - yolo-backend-bridge-network

  yolo-mongodb-alpine:
    image:  mongodb/mongodb-community-server
    ports:
      - "27017:27017"
    networks:
      - yolo-backend-bridge-network

networks:
  yolo-backend-bridge-network:
    driver: bridge



