#---
# update VMs pre step
- name: Update package cache
  hosts: all
  become: yes
  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes

- name: Ping all hosts
  hosts: all
  roles:
    - ping_role


# install_docker.yml
- name: Install Docker on all hosts
  hosts: all
  become: yes
  # vars_files:
  #   - roles/docker_roles/main.yml
  roles:
    - docker_role


# clone yolo
- name: Clone yolo git repo
  hosts: all
  become: yes
  roles:
    - clone_yolo_git


# pull and run mongodb container
- name: pull and run mongodb container
  hosts: mongodb
  become: yes
  roles:
    - run_mongodb_container
