
# task file for run_mongodb_container
- name: Pull MongoDB Docker image
  docker_image:
    name: "{{ docker_image_name }}"
    tag: "{{ docker_image_tag }}"
    source: pull

# create a docker volume
- name: Create Docker volume
  docker_volume:
    name: "{{ container_volume }}"

- name: Run MongoDB container
  docker_container:
    name: "{{ container_name }}"
    image: "{{ docker_image_name }}:{{ docker_image_tag }}"
    state: started
    restart_policy: on-failure
    ports: "{{ container_ports }}"
    volumes: "{{ container_volume }}:/var/lib/mongodb"
    tty: true