# Use the official MongoDB community server image as a base
FROM mongodb/mongodb-community-server:latest


# Expose the MongoDB port
EXPOSE 27017

VOLUME ["/var/lib/mongodb"]

# Command to run MongoDB
CMD ["mongod"]
