---
# tasks file for run_client_container
- name: Pull client Docker image
  community.docker.docker_image:
    name: "{{ docker_image_name }}"
    tag: "{{ docker_image_tag }}"
    source: pull

- name: Run client container
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "{{ docker_image_name }}:{{ docker_image_tag }}"
    state: started
    restart_policy: on-failure
    ports: "{{ container_ports }}"
    tty: true

    