---
# tasks file for run_backend_container
- name: Pull backend Docker image
  docker_image:
    name: "{{ docker_image_name }}"
    tag: "{{ docker_image_tag }}"
    source: pull

- name: Run backend container
  docker_container:
    name: "{{ container_name }}"
    image: "{{ docker_image_name }}:{{ docker_image_tag }}"
    state: started
    restart_policy: on-failure
    ports: "{{ container_ports }}"
    volumes: "{{ container_volumes }}"
    tty: true